project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: card-list
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css



