project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/erosrojas
      - icon: card-list
        href: https://erosrojas.github.io/test.html
format:
  html:
    theme: flatly
    css: styles.css



